Repository CastledChess/Api, pull requests merged in 2024-10, with the labels that each got.

#5 chore: Setup base project architecture
  .env.example
  src/app.module.ts
  src/app.service.ts
  src/common/constants/database.constants.ts
  src/common/constants/i18n.constants.ts
  src/common/constants/index.ts
  src/common/filters/.gitkeep
  src/common/interceptors/.gitkeep
  src/common/pipes/.gitkeep
  src/common/utils/.gitkeep
  src/config/database.config.ts
  src/config/i18n.config.ts
  src/database/database.module.ts
Labels: architecture

#6 chore: Setup swagger and update docker config
  .env.example
  Dockerfile
  README.md
  docker-compose.yml
  nginx/default.conf
  nginx/ssl/.gitkeep
  package-lock.json
  package.json
  src/app.module.ts
  src/common/constants/i18n.constants.ts
  src/common/constants/index.ts
  src/config/i18n.config.ts
  src/config/swagger.config.ts
  src/database/database.config.ts
  src/database/database.constants.ts
  src/main.ts
  tsconfig.json
Labels: documentation

#10 [WIP] feat: Génération de token JWT lors de l'inscription et de la connexion
  .env.example
  src/app.controller.spec.ts
  src/authentication/authentication.controller.ts
  src/authentication/authentication.module.ts
  src/authentication/authentication.service.spec.ts
  src/authentication/authentication.service.ts
  src/authentication/dto/request/create-user.dto.ts
  src/authentication/dto/request/login-request.dto.ts
  src/authentication/dto/response/authentication-response.dto.ts
  src/authentication/jwt-auth.guard.ts
  src/authentication/local-auth.guard.ts
  src/authentication/local.strategy.ts
  src/common/dto/user.dto.ts
  src/common/filters/.gitkeep
  src/common/filters/all-exceptions.filter.ts
  src/config/jwt.config.ts
  src/i18n/en/user.json
  src/i18n/en/validation.json
  src/i18n/fr/user.json
  src/i18n/fr/validation.json
  src/i18n/i18n.config.ts
  src/main.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: feature

#11 fix(build): Fix hot-reload in the docker container for windows
  tsconfig.build.json
Labels: bug

#22 feat: Authentication
  .gitignore
  nest-cli.json
  package.json
  src/app.module.ts
  src/authentication/authentication.controller.ts
  src/authentication/authentication.service.ts
  src/authentication/dto/create-user.dto.ts
  src/authentication/dto/login.dto.ts
  src/authentication/dto/request/create-user.dto.ts
  src/authentication/dto/request/login-request.dto.ts
  src/authentication/dto/response/authentication-response.dto.ts
  src/authentication/local-auth.guard.ts
  src/common/filters/all-exceptions.filter.ts
  src/i18n/en/validation.json
  src/i18n/fr/validation.json
  src/i18n/i18n.config.ts
  src/main.ts
  src/users/user.entity.ts
  src/users/users.service.ts
Labels: feature
